### PR TITLE
adding bootstrap-sass

### PR DESCRIPTION
**Pull request by jcouso**
Several bootstrap components don't work right now. The template is missing bootstrap-sass dependency

### CODE REVIEW

**Comment by Eschults** [comment]
Hi @jcouso thanks for reporting 🙏 
Could you explain exactly the bug(s) you encountered, on which components please?

**Comment by jcouso** [comment]
All clicking events for bootstrap elements were not working. Such as the navbar dropdrown(the dropdown would not appear) and flashes closing button(the flash would not close). (I only checked these two, before figuring out the solution). They all work fine after adding the bootstrap-sass to yarn.

**Comment by Eschults** [comment]
Which versions of rails / webpacker are you on? Can't reproduce the bug. Having both `bootstrap@3` and `bootstrap-sass` doesn't sounds right, you're duplicating code. You need to figure out why your javascript seems to fail, my guess is you're requiring javascript twice. Any errors in your JS console?

**Comment by jcouso** [comment]
I'm using rails 5.1.5 and webpacker 3.3.1. No errors on my JS console. You are right about duplication  the code, I removed bootstrap@3 and only left bootstrap-sass. Everything still works fine.

**Comment by Eschults** [comment]
Great! thanks for reporting 👍

**Pull request closed without merging**
